### ISSUE TITLE
Support customization through env variables

### ISSUE THREAD

**Issue by Yajo** [tarampampam/error-pages#16]
It would be awesome to be able to define error pages content by env variables.

It'd be sooo nice to be able to do something like:

```yaml
# docker-compose.yml
version: '3.4'

services:
  error-pages:
    image: tarampampam/error-pages:latest
    environment:
      CUSTOM_503: |
        <body>
          <div>My custom error page</div>
        </body>
```

**Comment by tarampampam** [comment]
What is the use case for this? Why do not use the ready templates?

**Comment by Yajo** [comment]
For instance I prefer to have a more human-friendly maintenance message for 502 and 503. Also, somebody might prefer corporate templates which wouldn't fit a generic project.

**Comment by modem7** [comment]
> For instance I prefer to have a more human-friendly maintenance message for 502 and 503. Also, somebody might prefer corporate templates which wouldn't fit a generic project.

Tbf, all you'd need to do there is modify the config.json file and build the project, and you could have the custom message of your choice. 

The HTML files are built during the dockerfile build stage, so not quite sure how @tarampampam would be able to put env variables in. Only way I can think of is via Nginx's http_sub_module - but that's massively processor intensive if not careful. 

It makes more sense to simplify it and edit the config.json and have several images depending on your use case. 

It takes about 20 seconds to build a new image.

**Comment by tarampampam** [comment]
@Yajo Hi there again! Sorry for the late response - I needed time to rewrite the whole application on go :)

Since v2.0.0 you can override the content of the templates. For example, now you can override the `ghost` template content on your choice:

https://github.com/tarampampam/error-pages/blob/29f024ebcc3c81cc01223ac558dec70e16ba6e3d/error-pages.yml#L5-L7

```yaml
# docker-compose.yml
version: '3.2'

services:
  error-pages:
    image: ghcr.io/tarampampam/error-pages:2.0.0
    environment:
      TEMPLATE_NAME: ghost
      GHOST_TEMPLATE_CONTENT: >
        <html>
        <body>{{ code }} - {{ message }}</body>
        </html>
    ports:
      - "8080:8080/tcp"
```

```bash
$ docker-compose up
```

![111](https://user-images.githubusercontent.com/7326800/135309424-7026cbcf-730d-4423-811d-12a6aab90cdc.png)

This issue can be closed now? :)

**Comment by Yajo** [comment]
Beautiful! Of course, thank you!
