### ISSUE TITLE
"Too big request header"

### ISSUE THREAD

**Issue by Quasarman** [tarampampam/error-pages#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] And it has nothing to do with Traefik

### Describe the bug

When the auth cookies for my website are present and I try to a non existing page I get "Too big request header" instead of the error page. When I clear said cookies I see my error page as expected.

### Steps to reproduce

1. Setup error pages
2. Set long token in cookies
3. Get "Too big request header" instead of error page

### Anything else?

I am not sure if this is a traefik issue, It does only happen with the error page container, accessing the normal webpage is fine with and without the auth cookies set.

**Comment by tarampampam** [comment]
Could you please provide an example (e.g., a curl command) to reproduce the error?

**Comment by Quasarman** [comment]
I think this is related: https://github.com/traefik/traefik/issues/8846

Maybe we can configure thr max header bytes for the error pages server aswell? Via a env variable or so.

I dont really have an example on hand since i dont want to provide my auth cookies (for obvious reasons).

**Comment by alphanoob1337** [comment]
I forked the project and introduced a new environment variable `READ_BUFFER_SIZE` which can be used to pass the desired maximum request size in bytes (including header and body). See pull request #244.

**Comment by Quasarman** [comment]
Very nice thank you! 😀

**Comment by tarampampam** [comment]
🚀 [v2.26.0](https://github.com/tarampampam/error-pages/releases/tag/v2.26.0)

**Comment by keitetran** [comment]
I have this error with traefik.

> Too big request header

My env 
> READ_BUFFER_SIZE: 1024

How to fix it ? Thank bro.

**Comment by alphanoob1337** [comment]
Just increase the number until it works. A larger read buffer has only one negative side-effect: the resource consumption is slightly higher. On an average server and normal load conditions this should not cause any problems since error-pages does not require many resources in the first place. But it might make it easier for someone with bad intentions to deliberately overload your server by sending many requests with a lot of payload data. So you also don't want to increase the read buffer to the maximum possible value.
